# Generated by Django 3.0 on 2021-10-27 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210917_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('movement_points', models.IntegerField(default=2)),
                ('can_cap', models.BooleanField(default=True)),
                ('hit_points', models.IntegerField(default=100)),
                ('attack_range', models.IntegerField(default=1)),
                ('base_attack', models.IntegerField(default=60)),
                ('base_defense', models.IntegerField(default=0)),
                ('unit_type', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.IntegerField(default=7),
        ),
        migrations.DeleteModel(
            name='Game_Piece',
        ),
        migrations.AddField(
            model_name='gamepiece',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_pieces', to='api.Game'),
        ),
        migrations.AddField(
            model_name='gamepiece',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_pieces', to=settings.AUTH_USER_MODEL),
        ),
    ]
