# Generated by Django 3.0 on 2021-09-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210917_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Piece',
            new_name='GamePiece',
        ),
    ]
