# Generated by Django 3.0 on 2021-09-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210917_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marine',
        ),
    ]
